image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -pl xchange-stream-binance,xchange-stream-bitcoinde,xchange-stream-bitfinex,xchange-stream-bitfinex2,xchange-stream-bitstamp,xchange-stream-cexio,xchange-stream-cexio2,xchange-stream-coinbasepro,xchange-stream-kraken,xchange-stream-poloniex,xchange-stream-poloniex2,xchange-stream-liquid -am"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - release